# Netlify configuration for olake.io
# Handles trailing slash redirects and other configurations

[build]
  publish = "build"
  command = "npm run build"

# Redirect all trailing slash URLs to non-trailing slash
[[redirects]]
  from = "/*/"
  to = "/:splat"
  status = 301
  force = true
  # Exclude root path
  conditions = {path = ["!/"]}

# Query parameter redirects for features tabs
[[redirects]]
  from = "/docs/features?tab=*"
  to = "/docs/features"
  status = 301

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

