import { useLocation } from '@docusaurus/router'

/**
 * Taxonomy pages (archive, authors, tags) are generated by three blog plugin
 * instances that otherwise produce identical titles/descriptions. This hook
 * works out which instance the current route belongs to so each page can get
 * its own title, description and h1.
 *
 * Instances (see docusaurus.config.js): olake-blog (/blog), iceberg-blog
 * (/iceberg) and customer-stories-blog (/customer-stories).
 */
const INSTANCES = {
  blog: {
    // Short label used in titles/h1: "Blog Archive", "Blog Authors", ...
    label: 'Blog',
    // Used in sentences: "... on the OLake blog"
    phrase: 'the OLake blog',
    // Used in author/tag page titles ('Posts by Name - Blog'). No "OLake" in it: the site title
    // already adds ' | OLake', and 'OLake Blog | OLake' named the site twice.
    titlePhrase: 'Blog',
    topics: 'data replication, Apache Iceberg and lakehouse guides'
  },
  iceberg: {
    label: 'Iceberg',
    phrase: 'the OLake Apache Iceberg blog',
    titlePhrase: 'Iceberg Blog',
    topics: 'Iceberg partitioning, catalogs, query engines and how-to guides'
  },
  'customer-stories': {
    label: 'Customer Stories',
    phrase: 'OLake customer stories',
    titlePhrase: 'Customer Stories',
    topics: 'case studies from teams replicating databases to Apache Iceberg'
  }
}

export function getBlogInstanceKey(pathname) {
  if (pathname === '/iceberg' || pathname.startsWith('/iceberg/')) return 'iceberg'
  if (pathname === '/customer-stories' || pathname.startsWith('/customer-stories/')) {
    return 'customer-stories'
  }
  return 'blog'
}

export default function useBlogInstance() {
  const { pathname } = useLocation()
  return { key: getBlogInstanceKey(pathname), ...INSTANCES[getBlogInstanceKey(pathname)] }
}

/** "One post" / "N posts" wording for descriptions (lowercase, no translate). */
export function postCountLabel(count) {
  return count === 1 ? '1 post' : `${count} posts`
}

/** Suffix for paginated listing pages so /page/2 etc. get distinct titles. */
export function pageSuffix(listMetadata) {
  const page = listMetadata?.page
  return page && page > 1 ? ` (Page ${page})` : ''
}

/** Longest <title> to aim for, including the " | OLake" suffix Docusaurus appends. */
const MAX_TITLE_LENGTH = 60
const SITE_SUFFIX = ' | OLake'

/**
 * Picks the first candidate that fits MAX_TITLE_LENGTH with the site suffix; when none fits, the
 * last (shortest) one is used. Candidates run from the most to the least descriptive.
 */
function fitTitle(candidates) {
  const fits = candidates.find((text) => text.length + SITE_SUFFIX.length <= MAX_TITLE_LENGTH)
  return fits ?? candidates[candidates.length - 1]
}

/**
 * <title> of a tag page: 'Posts tagged "OLake" - Blog'. It carries no post count, so it does
 * not change each time a post is published. `instance` is the object useBlogInstance() returns.
 */
export function tagPageTitle(label, instance, listMetadata) {
  const base = `Posts tagged "${label}"`
  const page = pageSuffix(listMetadata)
  return fitTitle([
    `${base} - ${instance.titlePhrase}${page}`,
    `${base} - ${instance.label}${page}`,
    `${base}${page}`
  ])
}

/**
 * <title> of an author page: 'Posts by Name - Blog'. No post count, for the same reason as
 * the tag pages.
 */
export function authorPageTitle(name, instance, listMetadata) {
  const base = `Posts by ${name}`
  const page = pageSuffix(listMetadata)
  return fitTitle([
    `${base} - ${instance.titlePhrase}${page}`,
    `${base} - ${instance.label}${page}`,
    `${base}${page}`
  ])
}

/** True on page 2 and later of a paginated listing (page 1 stays indexable). */
export function isPaginatedPage(listMetadata) {
  return Number(listMetadata?.page) > 1
}
