apiVersion: v1
kind: ConfigMap
metadata:
  name: olake-source-config # You can change this name if needed
  namespace: olake
data:
  source.json: |
    {
      "hosts": [
        "host1:27017",
        "host2:27017",
        "host3:27017"
      ],
      "username": "test",
      "password": "test",
      "authdb": "admin",
      "replica-set": "rs0",
      "read-preference": "secondaryPreferred",
      "srv": true,
      "database": "database",
      "max_threads": 5,
      "backoff_retry_count": 4,
      "chunking_strategy":""
    }
