---
apiVersion: v1
kind: ConfigMap
metadata:
  name: olake-destination-config # You can change this name if needed
  namespace: olake
data:
  destination.json: |
    {
    "type": "ICEBERG",
    "writer": {
      "catalog_type": "glue",
      "normalization": false,
      "iceberg_s3_path": "${ICEBERG_S3_PATH}",
      "aws_region": "${AWS_REGION}",
      "aws_access_key": "${AWS_ACCESS_KEY}",
      "aws_secret_key": "${AWS_SECRET_KEY}",
      "iceberg_db": "${ICEBERG_DB}",
      "grpc_port": 50051,
      "server_host": "localhost"
      }
    }
