apiVersion: v1
kind: ConfigMap
metadata:
  name: olake-catalog-config   # You can change this name if needed
  namespace: olake
data:
  catalog.json: |
    "selected_streams": {
      "otter_db": [
        {
          "partition_regex": "{now(),2025,YY}-{now(),06,MM}-{now(),13,DD}/{string_change_language,,}",
          "stream_name": "stream_0"
        },
        {
          "partition_regex": "{,1999,YY}-{,09,MM}-{,31,DD}/{latest_revision,,}",
          "stream_name": "stream_8"
        }
      ]
    }