import React from 'react'
import Link from '@docusaurus/Link'
import useBaseUrl from '@docusaurus/useBaseUrl'
import { useLocation } from '@docusaurus/router'
import clsx from 'clsx'

// The blog instances (docusaurus.config.js: olake-blog, customer-stories-blog, learn-blog, compare-blog)
const SECTIONS = [
  { label: 'Blog', path: '/blog' },
  { label: 'Customer Stories', path: '/customer-stories' },
  { label: 'Learn', path: '/learn' },
  { label: 'Compare', path: '/compare' }
]

// Sub pages generated by the blog plugin under each section
const SUB_PAGES = ['tags', 'authors', 'archive']

const capitalize = (str) => str.charAt(0).toUpperCase() + str.slice(1)
const readableName = (slug) => slug.split('-').map(capitalize).join(' ')

function Crumb({ item, index }) {
  return (
    <li itemProp='itemListElement' itemScope itemType='https://schema.org/ListItem'>
      <Link
        to={item.href}
        className={clsx('ob-crumbs__link', item.current && 'ob-crumbs__link--current')}
        itemProp='item'
        aria-current={item.current ? 'page' : undefined}
      >
        {item.label}
      </Link>
      {/* Schema.org markup for the breadcrumb item */}
      <meta itemProp='name' content={item.label} />
      <meta itemProp='position' content={String(index + 1)} />
    </li>
  )
}

function Trail({ items }) {
  return (
    <nav className='ob-crumbs' aria-label='Breadcrumb' itemScope itemType='https://schema.org/BreadcrumbList'>
      <ol>
        {items.map((item, index) => (
          <Crumb key={item.href} item={item} index={index} />
        ))}
      </ol>
    </nav>
  )
}

/** Home > Section > (Tags | Authors | Archive). `label` names a tag or author page. */
export default function BlogBreadcrumbs({ label }) {
  const location = useLocation()
  const home = useBaseUrl('/')

  const pathname = location.pathname
  const normalized = pathname.replace(/\/$/, '')
  const parts = pathname.split('/').filter(Boolean)
  const section = SECTIONS.find((s) => normalized === s.path || normalized.startsWith(`${s.path}/`))
  if (!section) return null

  const base = [
    { label: 'Home', href: home },
    { label: section.label, href: section.path }
  ]

  // Listing page and its /page/N pages
  if (normalized === section.path || normalized.startsWith(`${section.path}/page/`)) {
    return <Trail items={[base[0], { ...base[1], current: true }]} />
  }

  // Tags, authors and archive pages
  const sub = SUB_PAGES.find((s) => normalized === `${section.path}/${s}` || normalized.startsWith(`${section.path}/${s}/`))
  if (sub) {
    const items = [...base, { label: capitalize(sub), href: `${section.path}/${sub}` }]
    const slug = parts[2]
    if (slug && sub !== 'archive') {
      items.push({ label: label || readableName(slug), href: pathname, current: true })
    } else {
      items[items.length - 1].current = true
    }
    return <Trail items={items} />
  }

  // A post: no trail (it would only repeat the title; BlogLayout does not render this component there)
  return null
}
